version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.openjdk.jmh:jmh-generator-annprocess
    versions:
    - "1.27"
    - "1.28"
    - "1.29"
  - dependency-name: org.openjdk.jmh:jmh-core
    versions:
    - "1.27"
    - "1.28"
    - "1.29"
  - dependency-name: org.apache.maven.resolver:maven-resolver-util
    versions:
    - 1.6.2
  - dependency-name: org.apache.maven.resolver:maven-resolver-api
    versions:
    - 1.6.2
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
  - dependency-name: org.eclipse.sisu:org.eclipse.sisu.plexus
    versions:
    - 0.3.4
  - dependency-name: org.eclipse.aether:aether-util
    versions:
    - 1.1.0
  - dependency-name: org.eclipse.aether:aether-api
    versions:
    - 1.1.0
